import type { Question } from '../types';

export const mandatorySignQuestions: Question[] = [
  {
    id: 'q-mand-sign-1',
    text: 'Identify the road sign:',
    options: [
      { id: 'q-mand-sign-1o1', text: 'No entry for bicycles' },
      { id: 'q-mand-sign-1o2', text: 'Cyclists prohibited' },
      { id: 'q-mand-sign-1o3', text: 'Bicycle route ends' },
    ],
    correctAnswerId: 'q-mand-sign-1o2',
    explanation: 'This blue circular sign with bicycles crossed out by a red diagonal line indicates that cyclists are prohibited from this area.',
    subject: 'Mandatory Signs',
    imageUrl: '/images/signs/mandatorysigns/q-mand-sign-1.png',
    imageHint: 'no cyclists prohibited',
  },
  {
    id: 'q-mand-sign-2',
    text: 'Identify the road sign:',
    options: [
      { id: 'q-mand-sign-2o1', text: 'Compulsory route for tractors' },
      { id: 'q-mand-sign-2o2', text: 'Agricultural vehicles route' },
      { id: 'q-mand-sign-2o3', text: 'Tractors must use this route' },
    ],
    correctAnswerId: 'q-mand-sign-2o1',
    explanation: 'This blue circular sign with a tractor symbol indicates a compulsory route that must be used by tractors and agricultural vehicles.',
    subject: 'Mandatory Signs',
    imageUrl: '/images/signs/mandatorysigns/q-mand-sign-2.png',
    imageHint: 'compulsory tractor route',
  },
  {
    id: 'q-mand-sign-3',
    text: 'Identify the road sign:',
    options: [
      { id: 'q-mand-sign-3o1', text: 'Compulsory direction ahead' },
      { id: 'q-mand-sign-3o2', text: 'One-way street' },
      { id: 'q-mand-sign-3o3', text: 'Overtaking prohibited' },
    ],
    correctAnswerId: 'q-mand-sign-3o1',
    explanation: 'This sign mandates that traffic must proceed straight ahead only.',
    subject: 'Mandatory Signs',
    imageUrl: '/images/signs/mandatorysigns/q-mand-sign-3.png',
    imageHint: 'compulsory ahead',
  },
  {
    id: 'q-mand-sign-4',
    text: 'Identify the road sign:',
    options: [
      { id: 'q-mand-sign-4o1', text: 'Compulsory right turn' },
      { id: 'q-mand-sign-4o2', text: 'No right turn' },
      { id: 'q-mand-sign-4o3', text: 'Road bends right' },
    ],
    correctAnswerId: 'q-mand-sign-4o1',
    explanation: 'This sign indicates a compulsory right turn. Drivers must turn right.',
    subject: 'Mandatory Signs',
    imageUrl: '/images/signs/mandatorysigns/q-mand-sign-4.png',
    imageHint: 'compulsory right turn',
  },
  {
    id: 'q-mand-sign-5',
    text: 'Identify the road sign:',
    options: [
      { id: 'q-mand-sign-5o1', text: 'Roundabout ahead' },
      { id: 'q-mand-sign-5o2', text: 'Turn left or right' },
      { id: 'q-mand-sign-5o3', text: 'Compulsory roundabout circulation' },
    ],
    correctAnswerId: 'q-mand-sign-5o3',
    explanation: 'This sign indicates a roundabout ahead, and traffic must circulate in the direction shown by the arrows (typically anti-clockwise in right-hand traffic countries).',
    subject: 'Mandatory Signs',
    imageUrl: '/images/signs/mandatorysigns/q-mand-sign-5.png',
    imageHint: 'roundabout circulation',
  },
  {
    id: 'q-mand-sign-6',
    text: 'Identify the road sign:',
    options: [
      { id: 'q-mand-sign-6o1', text: 'Compulsory path for pedestrians' },
      { id: 'q-mand-sign-6o2', text: 'Pedestrians give way to vehicles' },
      { id: 'q-mand-sign-6o3', text: 'No pedestrians allowed' },
    ],
    correctAnswerId: 'q-mand-sign-6o1',
    explanation: 'This blue circular sign with a pedestrian symbol indicates a path that must be used by pedestrians.',
    subject: 'Mandatory Signs',
    imageUrl: '/images/signs/mandatorysigns/q-mand-sign-6.png',
    imageHint: 'pedestrian path',
  },
  {
    id: 'q-mand-sign-7',
    text: 'Identify the road sign:',
    options: [
      { id: 'q-mand-sign-7o1', text: 'Compulsory direction ahead' },
      { id: 'q-mand-sign-7o2', text: 'Compulsory direction right' },
      { id: 'q-mand-sign-7o3', text: 'One-way street' },
    ],
    correctAnswerId: 'q-mand-sign-7o2',
    explanation: 'This blue circular sign with a white arrow pointing right indicates a compulsory right turn. Drivers must turn right.',
    subject: 'Mandatory Signs',
    imageUrl: '/images/signs/mandatorysigns/q-mand-sign-7.png',
    imageHint: 'compulsory right turn',
  },
  {
    id: 'q-mand-sign-8',
    text: 'Identify the road sign:',
    options: [
      { id: 'q-mand-sign-8o1', text: 'Snow chains recommended' },
      { id: 'q-mand-sign-8o2', text: 'End of snow chain requirement' },
      { id: 'q-mand-sign-8o3', text: 'Snow chains compulsory' },
    ],
    correctAnswerId: 'q-mand-sign-8o3',
    explanation: 'This sign indicates that snow chains are compulsory on this section of road.',
    subject: 'Mandatory Signs',
    imageUrl: '/images/signs/mandatorysigns/q-mand-sign-8.png',
    imageHint: 'snow chains compulsory',
  },
  {
    id: 'q-mand-sign-9',
    text: 'Identify the road sign:',
    options: [
      { id: 'q-mand-sign-9o1', text: 'Minimum speed limit ends' },
      { id: 'q-mand-sign-9o2', text: 'Recommended speed 30 km/h' },
      { id: 'q-mand-sign-9o3', text: 'Compulsory minimum speed 30 km/h' },
    ],
    correctAnswerId: 'q-mand-sign-9o3',
    explanation: 'This blue circular sign with a number indicates a compulsory minimum speed. Vehicles must travel at least this speed if conditions allow.',
    subject: 'Mandatory Signs',
    imageUrl: '/images/signs/mandatorysigns/q-mand-sign-9.png',
    imageHint: 'minimum speed 30',
  },
  {
    id: 'q-mand-sign-10',
    text: 'Identify the road sign:',
    options: [
      { id: 'q-mand-sign-10o1', text: 'Turn left ahead' },
      { id: 'q-mand-sign-10o2', text: 'Proceed straight or turn left' },
      { id: 'q-mand-sign-10o3', text: 'Pass either side' },
    ],
    correctAnswerId: 'q-mand-sign-10o1',
    explanation: 'This sign mandates that traffic must turn left ahead.',
    subject: 'Mandatory Signs',
    imageUrl: '/images/signs/mandatorysigns/q-mand-sign-10.png',
    imageHint: 'turn left ahead',
  },
]; 