import type { Question } from '../types';

export const mandatorySignQuestions: Question[] = [
  {
    id: 'q-mand-sign-1',
    text: 'Identify the road sign:',
    options: [
      { id: 'q-mand-sign-1o1', text: 'Compulsory route for bicycles' },
      { id: 'q-mand-sign-1o2', text: 'Bicycle route ahead' },
      { id: 'q-mand-sign-1o3', text: 'Bicycle parking area' },
    ],
    correctAnswerId: 'q-mand-sign-1o1',
    explanation: 'This blue circular sign with a bicycle symbol indicates a compulsory route for bicycles. Cyclists must use this designated route.',
    subject: 'Mandatory Signs',
    imageUrl: '/images/signs/mandatorysigns/q-mand-sign-1.png',
    imageHint: 'compulsory bicycle route',
  },
  {
    id: 'q-mand-sign-2',
    text: 'Identify the road sign:',
    options: [
      { id: 'q-mand-sign-2o1', text: 'Compulsory route for tractors' },
      { id: 'q-mand-sign-2o2', text: 'Agricultural vehicles route' },
      { id: 'q-mand-sign-2o3', text: 'Tractors must use this route' },
    ],
    correctAnswerId: 'q-mand-sign-2o1',
    explanation: 'This blue circular sign with a tractor symbol indicates a compulsory route that must be used by tractors and agricultural vehicles.',
    subject: 'Mandatory Signs',
    imageUrl: '/images/signs/mandatorysigns/q-mand-sign-2.png',
    imageHint: 'compulsory tractor route',
  },
  {
    id: 'q-mand-sign-3',
    text: 'Identify the road sign:',
    options: [
      { id: 'q-mand-sign-3o1', text: 'Roundabout ahead' },
      { id: 'q-mand-sign-3o2', text: 'Compulsory roundabout circulation' },
      { id: 'q-mand-sign-3o3', text: 'Turn left or right' },
    ],
    correctAnswerId: 'q-mand-sign-3o2',
    explanation: 'This blue circular sign with arrows indicates a roundabout ahead, and traffic must circulate in the direction shown by the arrows (typically anti-clockwise in right-hand traffic countries).',
    subject: 'Mandatory Signs',
    imageUrl: '/images/signs/mandatorysigns/q-mand-sign-3.png',
    imageHint: 'roundabout circulation',
  },
  {
    id: 'q-mand-sign-4',
    text: 'Identify the road sign:',
    options: [
      { id: 'q-mand-sign-4o1', text: 'Compulsory route for trams' },
      { id: 'q-mand-sign-4o2', text: 'Tram route ahead' },
      { id: 'q-mand-sign-4o3', text: 'Tram stop ahead' },
    ],
    correctAnswerId: 'q-mand-sign-4o1',
    explanation: 'This blue circular sign with a tram symbol indicates a compulsory route for trams. Trams must use this designated route.',
    subject: 'Mandatory Signs',
    imageUrl: '/images/signs/mandatorysigns/q-mand-sign-4.png',
    imageHint: 'compulsory tram route',
  },
  {
    id: 'q-mand-sign-5',
    text: 'Identify the road sign:',
    options: [
      { id: 'q-mand-sign-5o1', text: 'Compulsory right turn' },
      { id: 'q-mand-sign-5o2', text: 'No right turn' },
      { id: 'q-mand-sign-5o3', text: 'Road bends right' },
    ],
    correctAnswerId: 'q-mand-sign-5o1',
    explanation: 'This blue circular sign with a white arrow pointing right indicates a compulsory right turn. Drivers must turn right.',
    subject: 'Mandatory Signs',
    imageUrl: '/images/signs/mandatorysigns/q-mand-sign-5.png',
    imageHint: 'compulsory right turn',
  },
  {
    id: 'q-mand-sign-6',
    text: 'Identify the road sign:',
    options: [
      { id: 'q-mand-sign-6o1', text: 'Compulsory route for vehicles' },
      { id: 'q-mand-sign-6o2', text: 'Vehicles may choose left or right' },
      { id: 'q-mand-sign-6o3', text: 'No vehicles allowed' },
    ],
    correctAnswerId: 'q-mand-sign-6o1',
    explanation: 'This blue circular sign with a vehicle symbol and branching arrows indicates a compulsory route for vehicles. The arrows show that vehicles must use this route and can choose to go left or right.',
    subject: 'Mandatory Signs',
    imageUrl: '/images/signs/mandatorysigns/q-mand-sign-6.png',
    imageHint: 'compulsory vehicle route with directional choice',
  },
  {
    id: 'q-mand-sign-7',
    text: 'Identify the road sign:',
    options: [
      { id: 'q-mand-sign-7o1', text: 'Compulsory direction ahead' },
      { id: 'q-mand-sign-7o2', text: 'Compulsory direction right' },
      { id: 'q-mand-sign-7o3', text: 'Compulsory diagonal direction' },
    ],
    correctAnswerId: 'q-mand-sign-7o3',
    explanation: 'This blue circular sign with a white diagonal arrow pointing down-right indicates a compulsory diagonal direction. Drivers must follow the direction shown by the arrow.',
    subject: 'Mandatory Signs',
    imageUrl: '/images/signs/mandatorysigns/q-mand-sign-7.png',
    imageHint: 'compulsory diagonal direction',
  },
  {
    id: 'q-mand-sign-8',
    text: 'Identify the road sign:',
    options: [
      { id: 'q-mand-sign-8o1', text: 'Bus stop ahead' },
      { id: 'q-mand-sign-8o2', text: 'No buses allowed' },
      { id: 'q-mand-sign-8o3', text: 'Compulsory route for buses' },
    ],
    correctAnswerId: 'q-mand-sign-8o3',
    explanation: 'This blue circular sign with a bus symbol indicates a compulsory route for buses. Buses must use this designated route.',
    subject: 'Mandatory Signs',
    imageUrl: '/images/signs/mandatorysigns/q-mand-sign-8.png',
    imageHint: 'compulsory route for buses',
  },
  {
    id: 'q-mand-sign-9',
    text: 'Identify the road sign:',
    options: [
      { id: 'q-mand-sign-9o1', text: 'Compulsory direction ahead' },
      { id: 'q-mand-sign-9o2', text: 'Compulsory direction right' },
      { id: 'q-mand-sign-9o3', text: 'Proceed straight or turn right' },
    ],
    correctAnswerId: 'q-mand-sign-9o3',
    explanation: 'This blue circular sign with two arrows (one straight, one right) indicates that vehicles must proceed straight ahead or turn right. Both directions are permitted.',
    subject: 'Mandatory Signs',
    imageUrl: '/images/signs/mandatorysigns/q-mand-sign-9.png',
    imageHint: 'proceed straight or turn right',
  },
  {
    id: 'q-mand-sign-10',
    text: 'Identify the road sign:',
    options: [
      { id: 'q-mand-sign-10o1', text: 'Compulsory path for horse riders' },
      { id: 'q-mand-sign-10o2', text: 'Horse riders prohibited' },
      { id: 'q-mand-sign-10o3', text: 'Horse crossing ahead' },
    ],
    correctAnswerId: 'q-mand-sign-10o1',
    explanation: 'This blue circular sign with a horse rider symbol indicates a compulsory path for horse riders. Horse riders must use this designated path.',
    subject: 'Mandatory Signs',
    imageUrl: '/images/signs/mandatorysigns/q-mand-sign-10.png',
    imageHint: 'compulsory path for horse riders',
  },
]; 