import type { Question } from '../types';

export const prohibitorySignsQuestions: Question[] = [
  {
    id: 'q-prohibit-1',
    text: 'Identify the road sign:',
    options: [
      { id: 'q-prohibit-1o1', text: 'Maximum speed 50 km/h' },
      { id: 'q-prohibit-1o2', text: 'Speed limit ends' },
      { id: 'q-prohibit-1o3', text: 'Minimum speed 50 km/h' },
    ],
    correctAnswerId: 'q-prohibit-1o2',
    explanation: 'This sign indicates the end of a previously imposed 50 km/h speed limit. National or other posted speed limits now apply.',
    subject: 'Prohibitory Signs',
    imageUrl: '/images/signs/prohibitory signs/q-prohibit-1.png',
    imageHint: 'speed limit ends',
  },
  {
    id: 'q-prohibit-2',
    text: 'Identify the road sign:',
    options: [
      { id: 'q-prohibit-2o1', text: 'Vehicles weighing heavier than indicated forbidden' },
      { id: 'q-prohibit-2o2', text: 'No entry for lorries' },
      { id: 'q-prohibit-2o3', text: 'Axle weight limit 5,4t' },
    ],
    correctAnswerId: 'q-prohibit-2o1',
    explanation: 'This sign prohibits vehicles with an actual weight exceeding 5,4 tonnes from proceeding.',
    subject: 'Prohibitory Signs',
    imageUrl: '/images/signs/prohibitory signs/q-prohibit-2.png',
    imageHint: 'weight limit 5.4t',
  },
  {
    id: 'q-prohibit-3',
    text: 'Identify the road sign:',
    options: [
      { id: 'q-prohibit-3o1', text: 'Agricultural vehicles route' },
      { id: 'q-prohibit-3o2', text: 'No entry for slow vehicles' },
      { id: 'q-prohibit-3o3', text: 'Tractors prohibited' },
    ],
    correctAnswerId: 'q-prohibit-3o3',
    explanation: 'This sign indicates that tractors and other specified agricultural vehicles are prohibited from this road.',
    subject: 'Prohibitory Signs',
    imageUrl: '/images/signs/prohibitory signs/q-prohibit-3.png',
    imageHint: 'no tractors',
  },
  {
    id: 'q-prohibit-4',
    text: 'Identify the road sign:',
    options: [
      { id: 'q-prohibit-4o1', text: 'Cyclists not permitted' },
      { id: 'q-prohibit-4o2', text: 'Cycle route ahead' },
      { id: 'q-prohibit-4o3', text: 'Shared path for pedestrians and cyclists' },
    ],
    correctAnswerId: 'q-prohibit-4o1',
    explanation: 'This sign means no entry for bicycles. Cyclists must find an alternative route.',
    subject: 'Prohibitory Signs',
    imageUrl: '/images/signs/prohibitory signs/q-prohibit-4.png',
    imageHint: 'no cyclists',
  },
  {
    id: 'q-prohibit-5',
    text: 'Identify the road sign:',
    options: [
      { id: 'q-prohibit-5o1', text: 'No parking zone' },
      { id: 'q-prohibit-5o2', text: 'Stopping and parking forbidden' },
      { id: 'q-prohibit-5o3', text: 'Clearway, no stopping on carriageway' },
    ],
    correctAnswerId: 'q-prohibit-5o2',
    explanation: 'This sign indicates that stopping and parking are forbidden along this section of road.',
    subject: 'Prohibitory Signs',
    imageUrl: '/images/signs/prohibitory signs/q-prohibit-5.png',
    imageHint: 'no stopping parking',
  },
  {
    id: 'q-prohibit-6',
    text: 'Identify the road sign:',
    options: [
      { id: 'q-prohibit-6o1', text: 'Speed limit 30 km/h applies' },
      { id: 'q-prohibit-6o2', text: 'End of all restrictions in zone' },
      { id: 'q-prohibit-6o3', text: 'End of the zone with speed limit' },
    ],
    correctAnswerId: 'q-prohibit-6o3',
    explanation: 'This sign marks the end of a zone where a specific speed limit (e.g., 30 km/h) was in force.',
    subject: 'Prohibitory Signs',
    imageUrl: '/images/signs/prohibitory signs/q-prohibit-6.png',
    imageHint: 'end speed zone',
  },
  {
    id: 'q-prohibit-7',
    text: 'Identify the road sign:',
    options: [
      { id: 'q-prohibit-7o1', text: 'Begin of a zone with speed limit' },
      { id: 'q-prohibit-7o2', text: 'Residential area, walking speed' },
      { id: 'q-prohibit-7o3', text: 'Recommended speed 30 km/h' },
    ],
    correctAnswerId: 'q-prohibit-7o1',
    explanation: 'This sign indicates the beginning of a zone where a specific speed limit (in this case, 30 km/h) applies.',
    subject: 'Prohibitory Signs',
    imageUrl: '/images/signs/prohibitory signs/q-prohibit-7.png',
    imageHint: 'begin speed zone 30',
  },
  {
    id: 'q-prohibit-8',
    text: 'Identify the road sign:',
    options: [
      { id: 'q-prohibit-8o1', text: 'Overtaking permitted' },
      { id: 'q-prohibit-8o2', text: 'End of the overtaking prohibition' },
      { id: 'q-prohibit-8o3', text: 'No overtaking by lorries' },
    ],
    correctAnswerId: 'q-prohibit-8o2',
    explanation: 'This sign indicates the end of a previously imposed overtaking prohibition. Standard overtaking rules now apply.',
    subject: 'Prohibitory Signs',
    imageUrl: '/images/signs/prohibitory signs/q-prohibit-8.png',
    imageHint: 'end no overtaking',
  },
  {
    id: 'q-prohibit-9',
    text: 'Identify the road sign:',
    options: [
      { id: 'q-prohibit-9o1', text: 'No entry for any vehicles' },
      { id: 'q-prohibit-9o2', text: 'Cyclists, mopeds and tractors prohibited' },
      { id: 'q-prohibit-9o3', text: 'Route for agricultural vehicles and cycles only' },
    ],
    correctAnswerId: 'q-prohibit-9o2',
    explanation: 'This sign prohibits entry for cyclists, mopeds, and tractors.',
    subject: 'Prohibitory Signs',
    imageUrl: '/images/signs/prohibitory signs/q-prohibit-9.png',
    imageHint: 'no cyclists mopeds tractors',
  },
  {
    id: 'q-prohibit-10',
    text: 'Identify the road sign:',
    options: [
      { id: 'q-prohibit-10o1', text: 'Motorcycles must use this lane' },
      { id: 'q-prohibit-10o2', text: 'Motorbikes - Motorcycles prohibited' },
      { id: 'q-prohibit-10o3', text: 'Motorcycle parking area' },
    ],
    correctAnswerId: 'q-prohibit-10o2',
    explanation: 'This sign indicates that motorcycles (motorbikes) are prohibited from using this road or area.',
    subject: 'Prohibitory Signs',
    imageUrl: '/images/signs/prohibitory signs/q-prohibit-10.png',
    imageHint: 'no motorcycles',
  },
]; 